version: '3'

services:
  app:
    image: ts-example
    build: .
    volumes:
      - ./:/app/
    ports:
      - 3456:3456
    command: node .
    environment:
      LOG_LVL: DEBUG
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
